import { useState } from 'react'
import { useNavigate } from 'react-router-dom'
import {
  User, Mail, Phone, Building2, Briefcase, Calendar, Clock,
  CalendarDays, Percent, ArrowLeft, ArrowRight, CheckCircle2
} from 'lucide-react'

function AddEmployee() {
  const navigate = useNavigate()

  const [name, setName] = useState('')
  const [email, setEmail] = useState('')
  const [phone, setPhone] = useState('')
  const [department, setDepartment] = useState('')
  const [post, setPost] = useState('')
  const [doj, setDoj] = useState('')
  const [goodPay, setGoodPay] = useState('')
  const [lta, setLta] = useState('')
  const [professionalTax, setProfessionalTax] = useState('')
  const [breakTime, setBreakTime] = useState('')
  const [workingDays, setWorkingDays] = useState('')

  const [error, setError] = useState('')
  const [isSubmitted, setIsSubmitted] = useState(false)
  const [generatedEmpId, setGeneratedEmpId] = useState('')

  const handleSubmit = (e) => {
    e.preventDefault()
    setError('')

    if (!name || !email || !phone || !department || !post || !doj) {
      setError('Please fill in all required fields.')
      return
    }

    // TODO: replace with real API call once backend is ready
    // Backend generates the Employee ID (EMP_ID format: OI + first two letters
    // of first/last name + join year + serial) and a first-time password,
    // then emails both credentials to the employee.
    // const res = await fetch('/api/employees', { method: 'POST', body: JSON.stringify({
    //   name, email, phone, department, post, doj,
    //   goodPay, lta, professionalTax, breakTime, workingDays,
    // }) })
    // const data = await res.json()
    // setGeneratedEmpId(data.empId)

    console.log('New employee:', { name, email, phone, department, post, doj, goodPay, lta, professionalTax, breakTime, workingDays })
    setGeneratedEmpId('(will be generated by backend)') // placeholder until wired up
    setIsSubmitted(true)
  }

  const resetForm = () => {
    setIsSubmitted(false)
    setName(''); setEmail(''); setPhone(''); setDepartment(''); setPost('')
    setDoj(''); setGoodPay(''); setLta(''); setProfessionalTax('')
    setBreakTime(''); setWorkingDays('')
  }

  const inputClass =
    'w-full bg-[#F9FAFB] border-2 border-[#E5E7EB] rounded-xl py-3.5 pl-11 pr-4 text-sm placeholder:text-[#C1C5CC] focus:outline-none focus:ring-4 focus:ring-[#6C5CE7]/15 focus:border-[#6C5CE7] focus:bg-white transition-all'

  if (isSubmitted) {
    return (
      <div className="min-h-screen w-full bg-[#F7F7FB] flex items-center justify-center p-6">
        <div className="bg-white/80 backdrop-blur-xl border border-white shadow-[0_20px_60px_rgba(108,92,231,0.2)] rounded-3xl p-10 max-w-md w-full text-center">
          <div className="w-16 h-16 rounded-full bg-[#ECFDF5] flex items-center justify-center mx-auto mb-6">
            <CheckCircle2 size={32} className="text-[#059669]" />
          </div>
          <h2 className="font-display text-2xl font-bold mb-3 tracking-tight">Employee added!</h2>
          <p className="text-[#6B7280] text-sm mb-2 leading-relaxed">
            <span className="font-semibold text-[#374151]">{name}</span> has been added to your organization.
          </p>
          <p className="text-xs text-[#9CA3AF] mb-8">
            Employee ID: <span className="font-semibold text-[#374151]">{generatedEmpId}</span> — credentials sent to{' '}
            <span className="font-semibold text-[#374151]">{email}</span>.
          </p>
          <div className="flex gap-3">
            <button
              onClick={resetForm}
              className="flex-1 bg-white border-2 border-[#E5E7EB] hover:border-[#6C5CE7] hover:text-[#6C5CE7] text-[#374151] text-sm font-semibold py-3 rounded-xl transition"
            >
              Add Another
            </button>
            <button
              onClick={() => navigate('/dashboard/admin')}
              className="flex-1 bg-gradient-to-r from-[#6C5CE7] via-[#8B7CF6] to-[#FF6B6B] text-white text-sm font-semibold py-3 rounded-xl shadow-lg shadow-[#6C5CE7]/30 hover:opacity-90 transition"
            >
              Back to Dashboard
            </button>
          </div>
        </div>
      </div>
    )
  }

  return (
    <div className="min-h-screen w-full bg-[#F7F7FB] text-[#111827] py-10 px-4 sm:px-8">
      <div className="max-w-3xl mx-auto">
        <button
          onClick={() => navigate('/dashboard/admin')}
          className="flex items-center gap-1.5 text-sm font-medium text-[#6B7280] hover:text-[#111827] transition mb-6"
        >
          <ArrowLeft size={16} />
          Back to Dashboard
        </button>

        <div className="mb-8">
          <h1 className="font-display text-3xl font-bold tracking-tight mb-2">Add New Employee</h1>
          <p className="text-[#6B7280] text-sm">Employee ID and a first-time password will be generated automatically.</p>
        </div>

        {error && (
          <div className="bg-[#FEF2F2] border border-[#FECACA] text-[#DC2626] text-sm rounded-xl px-4 py-3 mb-6">
            {error}
          </div>
        )}

        <form onSubmit={handleSubmit} className="space-y-6">
          {/* Basic Details */}
          <div className="bg-white/80 backdrop-blur-xl border border-white shadow-[0_20px_60px_rgba(108,92,231,0.15)] rounded-3xl p-6 sm:p-8">
            <h2 className="font-display text-lg font-bold tracking-tight mb-5">Basic Details</h2>
            <div className="grid sm:grid-cols-2 gap-5">
              <div className="sm:col-span-2">
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Full Name</label>
                <div className="relative">
                  <User size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="text" value={name} onChange={(e) => setName(e.target.value)} placeholder="Aisha Khan" required className={inputClass} />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Email</label>
                <div className="relative">
                  <Mail size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="email" value={email} onChange={(e) => setEmail(e.target.value)} placeholder="aisha.khan@acmecorp.com" required className={inputClass} />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Phone</label>
                <div className="relative">
                  <Phone size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="tel" value={phone} onChange={(e) => setPhone(e.target.value)} placeholder="+91 98765 43210" required className={inputClass} />
                </div>
              </div>
            </div>
          </div>

          {/* Organizational Details */}
          <div className="bg-white/80 backdrop-blur-xl border border-white shadow-[0_20px_60px_rgba(108,92,231,0.15)] rounded-3xl p-6 sm:p-8">
            <h2 className="font-display text-lg font-bold tracking-tight mb-5">Organizational Details</h2>
            <div className="grid sm:grid-cols-2 gap-5">
              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Department</label>
                <div className="relative">
                  <Building2 size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="text" value={department} onChange={(e) => setDepartment(e.target.value)} placeholder="Engineering" required className={inputClass} />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Post / Designation</label>
                <div className="relative">
                  <Briefcase size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="text" value={post} onChange={(e) => setPost(e.target.value)} placeholder="Backend Engineer" required className={inputClass} />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Date of Joining</label>
                <div className="relative">
                  <Calendar size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="date" value={doj} onChange={(e) => setDoj(e.target.value)} required className={inputClass} />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Working Days / Week</label>
                <div className="relative">
                  <CalendarDays size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="text" value={workingDays} onChange={(e) => setWorkingDays(e.target.value)} placeholder="5" className={inputClass} />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Break Time</label>
                <div className="relative">
                  <Clock size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="text" value={breakTime} onChange={(e) => setBreakTime(e.target.value)} placeholder="1 hour" className={inputClass} />
                </div>
              </div>
            </div>
          </div>

          {/* Pay Structure */}
          <div className="bg-white/80 backdrop-blur-xl border border-white shadow-[0_20px_60px_rgba(108,92,231,0.15)] rounded-3xl p-6 sm:p-8">
            <div className="flex items-center gap-2 mb-5">
              <h2 className="font-display text-lg font-bold tracking-tight">Pay Structure</h2>
              <span className="text-xs text-[#9CA3AF] font-medium bg-[#F3F4F6] px-2 py-0.5 rounded-full">Optional</span>
            </div>
            <div className="grid sm:grid-cols-3 gap-5">
              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Good Pay (%)</label>
                <div className="relative">
                  <Percent size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="number" value={goodPay} onChange={(e) => setGoodPay(e.target.value)} placeholder="10" className={inputClass} />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">LTA (%)</label>
                <div className="relative">
                  <Percent size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="number" value={lta} onChange={(e) => setLta(e.target.value)} placeholder="8" className={inputClass} />
                </div>
              </div>

              <div>
                <label className="text-xs font-semibold text-[#374151] mb-2 block uppercase tracking-wide">Professional Tax (%)</label>
                <div className="relative">
                  <Percent size={18} className="absolute left-4 top-1/2 -translate-y-1/2 text-[#9CA3AF]" />
                  <input type="number" value={professionalTax} onChange={(e) => setProfessionalTax(e.target.value)} placeholder="2" className={inputClass} />
                </div>
              </div>
            </div>
          </div>

          <button
            type="submit"
            className="w-full bg-gradient-to-r from-[#6C5CE7] via-[#8B7CF6] to-[#FF6B6B] bg-[length:200%_auto] hover:bg-right transition-all duration-500 rounded-xl py-4 font-semibold text-sm flex items-center justify-center gap-2 shadow-xl shadow-[#6C5CE7]/30 text-white active:scale-[0.98]"
          >
            Add Employee
            <ArrowRight size={18} />
          </button>
        </form>
      </div>
    </div>
  )
}

export default AddEmployee